### ISSUE TITLE
enable visualization of 3 canonical planes like knossos does

### ISSUE THREAD

**Issue by alexbaden** [neurodata/ndviz#1]
@brainmaps wants this

( @jovo -- moved from OCP repo to the new viz repo! )
- [ ] Enable visualization through either the xy, yz, or xz plane 
- [ ] Display each plane side by side in the viewer (a la knossos)

**Comment by jovo** [comment]
nooice!

On Fri, Oct 23, 2015 at 11:51 AM, Alex Baden notifications@github.com
wrote:

> @brainmaps https://github.com/brainmaps wants this
> 
> ( @jovo https://github.com/jovo -- moved from OCP repo to the new viz
> repo! )
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/NeuroDataViz/issues/1.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by alexbaden** [comment]
This is going to require a complete rewrite of the way I process tiles. I'm going to push this back to next month / early 2016. I've updated the top post with the pieces required.

**Comment by jovo** [comment]
another option is to just enable the user to dynamically switch between the 3 planes.
could be an easier option first.

**Comment by jovo** [comment]
another request for 3 canonical views

**Comment by alexbaden** [comment]
@randalburns and @kunallillaney need to modify the catmaid tile service to spit out isotropic tiles for xz and yz planes. We are on it!

**Comment by alexbaden** [comment]
https://github.com/neurodata/ndstore/issues/327

**Comment by alexbaden** [comment]
- [ ] xz and yz have different z-indices on zoom (because z-index is now voxel valued not slice valued) 

**add isotropic flag?**

**Comment by alexbaden** [comment]
For free with neuroglancer: https://github.com/neurodata/ndviz/tree/neuroglancer
