### ISSUE TITLE
add other tiles from PAG elegans stack

### ISSUE THREAD

**Issue by jovo** [neurodata/ndviz#108]
waiting on scott to send them.
seems like may would be a good deadline for this?

💑  (is the emoticon for enthusiastically collaborating!

**Comment by alexbaden** [comment]
Nah, Friday should be a good deadline. The transfer is already in progress
and is only 30GB, so I expect it will be done later today or tomorrow.
Friday at the very latest! 😎

**Comment by alexbaden** [comment]
Eating my words... this is going to take more work because we don't have the existing data format. I'll re-evaluate and update with a milestone by the end of the week.

**Comment by alexbaden** [comment]
Check it out! 

http://viz.neurodata.io/cook16/PAG/

Seems to match CATMAID?
http://openconnecto.me/catmaid/pid=10&zp=20475&yp=11515&xp=16635&tool=navigator&sid0=22&s0=3 (slice 315 in that view)

**Comment by jovo** [comment]
👌
