### ISSUE TITLE
channels in AT data

### ISSUE THREAD

**Issue by erikbloss** [neurodata/ndviz#110]
the FLAG channel actually displays the EGFP channel, and vice versa. It would be best to rename the present FLAG channel as EGFP, but keep the color green. thanks, erik

**Comment by alexbaden** [comment]
Sorry about that -- I switched the two channels. Did that fix it?

**Comment by erikbloss** [comment]
Hi Alex,
You’ve indeed switched them, but this time two new channels need to be switched.

channel 0 (anti_synaptophysin), which looks like small punch across nearly the whole image, should be blue- it is now both blue (correctly labeled as anti_synaptophysin) and shown in a second channel (incorrectly labeled as anti_gfp) in green.
 Channel 1 (anti_FLAG), is correctly labeled red. and channel 2 should be anti_gfp in green actually shows the synaptophysin labeling in green.

thanks for all your help and I’m sorry this is a pain in the ass!  erik

On Apr 22, 2016, at 11:14 AM, Alex Baden notifications@github.com wrote:

Sorry about that -- I switched the two channels. Did that fix it? 
—
You are receiving this because you authored the thread.
Reply to this email directly or 
view it on GitHub

**Comment by alexbaden** [comment]
No worries -- I've switched anti_gfp to be channel2. I think that fixed everything. Third times the charm?
