### ISSUE TITLE
add a scale bar 

### ISSUE THREAD

**Issue by alexbaden** [neurodata/ndviz#121]

**Comment by ailey** [comment]
@jovo & @perlman : scalebar would be awesome - top priority for neuroscientists (& helps demonstrate the zoom feature!)

**Comment by alexbaden** [comment]
See http://brainviz1.cs.jhu.edu/ndv/Fear199/Grayscale/xy/3/1240/928/500/ for first pass. Should be live on all the nd data within the next week.
