### ISSUE TITLE
can't control the image stats for each overlay

### ISSUE THREAD

**Issue by jovo** [neurodata/ndviz#133]
when there are more than 2 overlay channels, the box extends below my screen.
two possibly easy fixes:
- have a dropbox box to select which channel, and then only show controls for that channel
- make the whole box scroll.

**Comment by alexbaden** [comment]
As of https://github.com/neurodata/ndviz/commit/826134c171fdf56d08f51e105fa2e86327b209a8 all the permanent toolboxes/controls now scroll. Should be up on brainviz soon.
