### ISSUE TITLE
Account for seelviz

### ISSUE THREAD

**Issue by jonl1096** [neurodata/ndviz#156]
The Seelviz team working with the CLARITY brains needs an account on ndviz so we can create projects.

**Comment by toekneesunshine** [comment]
@jovo @gkiar

**Comment by jovo** [comment]
@alexbaden little help?

**Comment by alexbaden** [comment]
Discussed with @gkiar. You should be able to do what you're trying to do without an account. I gave Greg some pointers -- he'll pass them along. You can try the URL / tokenview interface and report back.
