### ISSUE TITLE
docker instructions

### ISSUE THREAD

**Issue by fcollman** [neurodata/ndviz#158]
your docker instructions are not up to date..

you should add
1) Edit the Dockerfile to include the username and password you put into the settings_secret.py file
2) Edit the settings.py file to comment out the #FORCE_SCRIPT_NAME= 
or at least explain when you would want or would not want to do this...

**Comment by alexbaden** [comment]
Dockerfile updated for ndviz v2. Should be much easier now that there isn't an associated database.
