### ISSUE TITLE
Need to refresh tiles after updating window range

### ISSUE THREAD

**Issue by kkutten1** [neurodata/ndviz#162]
So I changed the start and end window of the grayscale2 channel to 0 and 300 for project [myNewToken].  Unfortunately some of the tiles appear to be based on the old window settings (which were 100 and 650).  For example...
http://viz.neurodata.io/[myNewToken]/grayscale2/xy/0/388/437/500/
...is still based on the old window settings but ...
http://viz.neurodata.io/[myNewToken]/grayscale2/xy/0/388/437/499/
... is correctly based on the new settings.  How can I manually refresh the tiles

**Comment by alexbaden** [comment]
Your old tiles got cached (probably from viewing them previously). I flushed the cache -- should be good to go now.
