### ISSUE TITLE
ndviz does not respect scaling parameters

### ISSUE THREAD

**Issue by kkutten1** [neurodata/ndviz#165]
When switching from resolution 0 to resolution 1 by zooming out with the mouse wheel, ndviz adjusts the x and y coordinate but fails to adjust the z coordinate.  Thus the wrong z slice is displayed upon zooming out.  For example

http://viz.neurodata.io/155DLS_tail_to_ara3/grayscale4/0/500/500/500/

This occurs despite the fact that this token has isotropic ("xyz") scaling parameter indicating that scaling occurs in all 3 dimensions

http://openconnecto.me/ocp/ca/155DLS_tail_to_ara3/info/

**Comment by alexbaden** [comment]
The "zoom" in ndviz is only with respect to x and y. When zooming in or out, you are traversing the resolution hierarchy for an xy-slab within the 3D volume. Navigating through z-indices (traversing between slabs) is separate functionality. So, I think ndviz is working as expected here.

**Comment by alexbaden** [comment]
This should be resolved in v2.
