### ISSUE TITLE
add channels feature to render data source

### ISSUE THREAD

**Issue by fcollman** [neurodata/ndviz#178]
The newest version of render has a feature of 'channels' which you can have multiple images that all get the same transformations... the rest api for jpg cutouts now takes the optional keyword argument 'channels=$channel_name'.  If you could add that as a passthrough like minIntensity and maxIntensity it would enable the feature for ndviz sources.  Additionally I have this PR in to render https://github.com/saalfeldlab/render/pull/56.  If we get that accepted, then one can query the stackMetaData to get a list of channels available in that stack.  It would be nice to extend the add data source UI to use this information to allow channels to be selected more easily. 

I might suggest the URL shortcut of render://http://host:port/owner/project/stack/channel that will get reformed dynamically as you already have it.

**Comment by alexbaden** [comment]
https://github.com/google/neuroglancer/pull/59
