### ISSUE TITLE
investigate applying filters with an external JS library

### ISSUE THREAD

**Issue by j6k4m8** [neurodata/ndviz#24]
So, CSS filters are slow. _Reeealll_ slow. And even once there's nothing changing on the page, the filters continue to try to run as fast as possible, which means that if you have a complex filter like `opacity`, you're going to max out at a few FPS even when nothing's changing. 

I was trying to think of the "right" way to fix this. At least in my experience, libraries like Processing.js and its cousin, p5.js, handle this far better and far faster. I think the next step in terms of optimizing filters is running the images through one of those libraries (probably p5 will be easier to integrate) before rendering them, so that instead of applying CSS filters, you're rendering the image behind the scenes with p5 and then simply showing it to the user.

Happy to discuss more; this may be too big of a change to really be worth it, but if we want to bump up our render speed once we apply filters, this is the way to do it.*

\* Except for opacity, which should be done with the `opacity: #` css rule, not the `filter: opacity(#)` rule, which I believe is what Leaflet is doing... that one's an easy fix.

**Comment by alexbaden** [comment]
Using camanjs: http://camanjs.com/

It's ok. Kindof slow. Will have to look into optimizing it or replacing it with WebGL.
