### ISSUE TITLE
auto-populate channels when adding a layer, given the token

### ISSUE THREAD

**Issue by jovo** [neurodata/ndviz#29]

**Comment by wrgr** [comment]
This is interesting...sometimes this makes tons of sense, but sometimes we
have 100 different channels and you wouldn't want to do this.  What about
making them available to add?

Best,
Will

On Wed, Nov 4, 2015 at 12:21 AM, joshua vogelstein <notifications@github.com

**Comment by alexbaden** [comment]
I think the idea is to have a channels dropdown which lets you add other channels in a current project that may not have been specified, initially.

**Comment by alexbaden** [comment]
This functionality has been added  to the add data form. 

Of course, when you have 100s of channels, this won't look very good. 

But we'll cross that bridge when we come to it.
