### ISSUE TITLE
a list of good urls published *somewhere*

### ISSUE THREAD

**Issue by jovo** [neurodata/ndviz#30]
doesn't matter where, but if you manually generated a list of urls that i could use to show/look at data, that would be super helpful.  can me in the readme of the datasets repo, for example...

**Comment by alexbaden** [comment]
http://neurodata.io/projects

**Comment by jovo** [comment]
this is amazeballs!!

can i make 1 minor request: for each of the 8  projects, can the "visualize" links just link to the appropriate viz page (either a dataview or a project)?

**Comment by alexbaden** [comment]
Done, sort of. Native CATMAID stacks still need to be viewed in CATMAID (unless we ingest them). I left all the CATMAID links too, we will need to sort out what publications require keeping a CATMAID link and what don't. But, all the projects with NDV support now have a NDV link.

**Comment by jovo** [comment]
cool!
is there any reason to have the links on the bottom still?
also, is there any reason that the c. elegans projects didn't get
neurodataviz projects?

On Sat, Feb 20, 2016 at 10:40 AM, Alex Baden notifications@github.com
wrote:

> Closed #30 https://github.com/neurodata/NeuroDataViz/issues/30.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/NeuroDataViz/issues/30#event-557600950.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by alexbaden** [comment]
Links on the bottom -- no. We should make a thread for that in website
though and discuss Monday. For NDV purposes it's all the same.

The two c elegant other than bhatla are CATMAID stacks, I believe. I could
be wrong, though.

**Comment by jovo** [comment]
ah, i see, ok, let's discuss monday.

On Sat, Feb 20, 2016 at 7:21 PM, Alex Baden notifications@github.com
wrote:

> Links on the bottom -- no. We should make a thread for that in website
> though and discuss Monday. For NDV purposes it's all the same.
> 
> The two c elegant other than bhatla are CATMAID stacks, I believe. I could
> be wrong, though.
> On Sat, Feb 20, 2016 at 19:15 joshua vogelstein notifications@github.com
> wrote:
> 
> > cool!
> > is there any reason to have the links on the bottom still?
> > also, is there any reason that the c. elegans projects didn't get
> > neurodataviz projects?
> > 
> > On Sat, Feb 20, 2016 at 10:40 AM, Alex Baden notifications@github.com
> > wrote:
> > 
> > > Closed #30 https://github.com/neurodata/NeuroDataViz/issues/30.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/neurodata/NeuroDataViz/issues/30#event-557600950.
> > 
> > ## 
> > 
> > the glass is all full: half water, half air.
> > neurodata.io
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/neurodata/NeuroDataViz/issues/30#issuecomment-186706636
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/NeuroDataViz/issues/30#issuecomment-186706856
> .

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by jovo** [comment]
So, we'll clarify on the page the difference and close this ?

On Saturday, February 20, 2016, joshua vogelstein jovo@jhu.edu wrote:

> ah, i see, ok, let's discuss monday.
> 
> On Sat, Feb 20, 2016 at 7:21 PM, Alex Baden <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > Links on the bottom -- no. We should make a thread for that in website
> > though and discuss Monday. For NDV purposes it's all the same.
> > 
> > The two c elegant other than bhatla are CATMAID stacks, I believe. I could
> > be wrong, though.
> > On Sat, Feb 20, 2016 at 19:15 joshua vogelstein <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> > 
> > > cool!
> > > is there any reason to have the links on the bottom still?
> > > also, is there any reason that the c. elegans projects didn't get
> > > neurodataviz projects?
> > > 
> > > On Sat, Feb 20, 2016 at 10:40 AM, Alex Baden <notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > > wrote:
> > > 
> > > > Closed #30 https://github.com/neurodata/NeuroDataViz/issues/30.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/neurodata/NeuroDataViz/issues/30#event-557600950
> > > > .
> > > 
> > > ## 
> > > 
> > > the glass is all full: half water, half air.
> > > neurodata.io
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/neurodata/NeuroDataViz/issues/30#issuecomment-186706636
> > > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/neurodata/NeuroDataViz/issues/30#issuecomment-186706856
> > .
> 
> ## 
> 
> the glass is all full:  half water, half air.
> neurodata.io

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by alexbaden** [comment]
Updated http://neurodata.io/projects

**Comment by wrgr** [comment]
@alexbaden - this looks really nice!!!

**Comment by alexbaden** [comment]
Thanks! But @j6k4m8 deserves the credit. I'm just really good with `ctrl+c` and `ctrl+v`

**Comment by jovo** [comment]
+1

On Mon, Feb 22, 2016 at 8:43 PM, Alex Baden notifications@github.com
wrote:

> Thanks! But @j6k4m8 https://github.com/j6k4m8 deserves the credit. I'm
> just really good with ctrl+c and ctrl+v
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/NeuroDataViz/issues/30#issuecomment-187468839
> .

## 

the glass is all full:  half water, half air.
neurodata.io
