### ISSUE TITLE
link to repo with ROIs & an atlas

### ISSUE THREAD

**Issue by jovo** [neurodata/ndviz#36]
CLARITY would be an example, @kkutten1 uploaded 2 different mouse atlases.

MNI152 is another example, will/greg are working on that.
we should have a good working example by thanksgiving.

this is a task that @alexbaden can complete when grelliam finishes, i'm not sure when that will be though.

**Comment by alexbaden** [comment]
What's the action item for me here? Seems like w/ the manage interface we should be able to get this done?

**Comment by jovo** [comment]
somebody (eg, @kkutten1 or @j6k4m8 ) would make RAMON objects with names that @alexbaden can point to in ndv

**Comment by alexbaden** [comment]
I made an issue in internal to handle all the different moving parts.
