### ISSUE TITLE
"No metadata for this project"

### ISSUE THREAD

**Issue by jovo** [neurodata/ndviz#38]
is written even when there is metatdata, eg
http://brainviz1.cs.jhu.edu/ndv/kharris15apical/em,ramon_test/3/507/469/90/#

**Comment by alexbaden** [comment]
That's coming from the LIMS system. Once LIMS is up and running, NDV will
pull LIMS metadata automatically. Perhaps I need a better phrase there?

Alex

**Comment by alexbaden** [comment]
Updated to `No LIMS metadata for this project` pending LIMS integration with OCP.
