### ISSUE TITLE
Token name altered internally before fetching image from CATMAID

### ISSUE THREAD

**Issue by j6k4m8** [neurodata/ndviz#50]
I'm looking at the [`kasthuri2015_ramon_v1`](http://viz.neurodata.io/kasthuri2015_ramon_v1/) annotations. No annotations show up in the default view. When I check what files are being requested over the wire, it looks like the token name is being truncated before rendering.

We should be requesting:
`http://openconnecto.me/ocp/catmaid/`<b>`kasthuri2015_ramon_v1`</b>`/synapses/xy/1200/3_1_3.png`

But instead we request:
`http://openconnecto.me/ocp/catmaid/`<b>`kasthuri2015_ramon`</b>`/synapses/xy/1200/3_1_3.png`.

Perhaps we're splitting on the `_` character..? Or after the 18th character?

**Comment by alexbaden** [comment]
Can you send me the NDV URL?

Alex

**Comment by j6k4m8** [comment]
http://viz.neurodata.io/kasthuri2015_ramon_v1/

![image](https://cloud.githubusercontent.com/assets/693511/11997102/d9b3529e-aa40-11e5-8d97-8025050e0d21.png)

**Comment by j6k4m8** [comment]
[this](https://github.com/openconnectome/NeuroDataViz/blob/master/ndv/views.py#L97) looks suspicious to me. traced it back jquery > django html > django views.py but I may be on the wrong track

**Comment by alexbaden** [comment]
I rewrote the URL processing in the latest release, so I wouldn't poke
around too much. There's also some divergence between tokenview and project
view (/project/<<vizproject>>) that I need to rectify. I'll look at this
for the December release.

**Comment by j6k4m8** [comment]
when should i check back to see the next release? I'm hoping to use that project for some Things

**Comment by alexbaden** [comment]
http://viz.neurodata.io/kasthuri2015_ramon_v1/xy/3/1265/2182/1100/

Seems good to go!

**Comment by j6k4m8** [comment]
yay!
