### ISSUE TITLE
be able to visualize image stacks

### ISSUE THREAD

**Issue by jovo** [neurodata/ndviz#54]
currently, when somebody gives us a large dataset, we cannot provide visualization capabilities for months, as we wait to ingest, and then propagate.

however, if ix let us look at image stacks (eg, in CATMAID format), we could ingest in the background, 
and then when ingest and propagate are both done, just update the pointer in the backend.

this will also be important for proofreading, meaning, some data is not good enough to align/color correct/ingest, so, as data comes off the scope, we want to visualize it immediately, even before proper aligning.

given that datascope probably won't work for us again, and that we won't have everything in the cloud for a few months, this seems like it would be a really great function to make asap.

@randalburns @kunallillaney thoughts?

**Comment by alexbaden** [comment]
"stackview"

**Comment by jovo** [comment]
brilliant

On Tue, Jan 5, 2016 at 9:05 PM, Alex Baden notifications@github.com wrote:

> "stackview"
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/NeuroDataViz/issues/54#issuecomment-169195979
> .

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by jovo** [comment]
this was redundant with #28
