### ISSUE TITLE
point CATMAID at david data

### ISSUE THREAD

**Issue by jovo** [neurodata/ndviz#55]
@kunallillaney can tell you where it is and stuff.

**Comment by kunallillaney** [comment]
@jovo His data is in slices not CATMAID tiles. So basically there are 16000 TIF images(each about 1.2GB). How will this work with CATMAID? I can write a script to convert his data into CATMAID format but his data is larger than 16TB(around 17TB uncompressed) but we do not have a single data array on the DSP's with that much space to host that data. Currently his data is partially stored on the ZFS shared Filesystem(which are not always online as per Lance) and on bg1dev in compressed format.
@randalburns

**Comment by jovo** [comment]
@kunallillaney interesting.  he used CATMAID, i thought on all his data, so i assumed he did a CATMAID export.  maybe it will be easier to update ndv to be able to look directly at images @alexbaden ?

**Comment by jovo** [comment]
@alexbaden kunal and i spoke, it seems that the easiest thing would be to point either CATMAID or ndv (whichever you think is easier) at data that we post (in CATMAID form) to a public S3 bucket.

note, this will require him to send us data again, in CATMAID form.

@kunallillaney is gonna put a small CATMAID stack in an open S3 bucket to try.

sound reasonable?

**Comment by alexbaden** [comment]
Handled offline.
