### ISSUE TITLE
only load layers when their opacity is > 0

### ISSUE THREAD

**Issue by alexbaden** [neurodata/ndviz#6]
Will likely be implemented as allowing the user to enable / disable a layer w/out removing it permanently

**Comment by jovo** [comment]
we don't need this anymore, now that you implemented the add channel thing, right?

**Comment by alexbaden** [comment]
Well, lets say you load 15 layers and set 10 opacities to 0. NDV is still going to make 15 web requests x <<number of tiles / layer>>. Even though you only want to look at 5 layers. So, modifying leaflet to only load layers with opacity > 0 might not be a bad idea. The trick is getting leaflet to reload layers if the opacity is set above 0. I think it's worth investigating further as part of the general goal of speeding things up for multi-channel datasets.

**Comment by jovo** [comment]
ok

On Tue, Jan 26, 2016 at 4:45 PM, Alex Baden notifications@github.com
wrote:

> Well, lets say you load 15 layers and set 10 opacities to 0. NDV is still
> going to make 15 web requests x <>. Even though you only want to look at 5
> layers. So, modifying leaflet to only load layers with opacity > 0 might
> not be a bad idea. The trick is getting leaflet to reload layers if the
> opacity is set above 0. I think it's worth investigating further as part of
> the general goal of speeding things up for multi-channel datasets.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/NeuroDataViz/issues/6#issuecomment-175246573
> .

## 

the glass is all full:  half water, half air.
neurodata.io
