### ISSUE TITLE
kristina15

### ISSUE THREAD

**Issue by jovo** [neurodata/ndviz#74]
http://viz.neurodata.io/kristina15/

can't see this?
@mrae

**Comment by alexbaden** [comment]
http://viz.neurodata.io/kristina15/dapi_1stA/xy/0/848/6492/0/

Appears to not be propagated. I started a propagate for dapi, if that works I can run the rest.

But, you wouldn't be able to view the link you sent anyway -- there are too many channels. You'll need to select subsets of channels (best way to do that is to load one and use the "+" button) and/or create a dataview with a few subsets of channels grouped as VizProjects.

**Comment by jovo** [comment]
ok

@alexbaden - can you send @mrae a link to the docs explaining how to make
dataviews and projects?

@mrae - can you make a ndviz project for this token, with 7 dataviews, one
per "marker type"? (i can elaborate in person once you understand how to
make dataviews)

thanks

On Mon, Feb 22, 2016 at 8:30 AM, Alex Baden notifications@github.com
wrote:

> http://viz.neurodata.io/kristina15/dapi_1stA/xy/0/848/6492/0/
> 
> Appears to not be propagated. I started a propagate for dapi, if that
> works I can run the rest.
> 
> But, you wouldn't be able to view the link you sent anyway -- there are
> too many channels. You'll need to select subsets of channels (best way to
> do that is to load one and use the "+" button) and/or create a dataview
> with a few subsets of channels grouped as VizProjects.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/NeuroDataViz/issues/74#issuecomment-187173404
> .

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by alexbaden** [comment]
Handled the NDV side.

**Comment by jovo** [comment]
meaning you taught @mrae how to do it?

On Tue, Feb 23, 2016 at 1:51 PM, Alex Baden notifications@github.com
wrote:

> Handled the NDV side.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/NeuroDataViz/issues/74#issuecomment-187839027
> .

## 

the glass is all full:  half water, half air.
neurodata.io
